language: ruby
rvm:
- 2.4
script:
- bundle exec rails db:migrate
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: XblFwztU583ERDNpTPiJmdbpT2+lhicyO5ek/3ta5MAs3ygGlhAUU0/ebJUS8hOtGHF24u8OvMsBQhWZBfjDDPumKFfy6lyDajPqmYwtvU0EjVY9NGALZAnSTLQm065wEMzpm3tYMpbgZwOCcsMA7bU3mAE8gSAQuLtTZFHMeutfe8mxb343X81smc1v9jf0jVkiH+BolV50Bdz3Vz/NSodeAKZbtUjMzJKW9X5yR19ttEaP8qkREvJ90AEXnxu1Yn5KdhYPo9/UqSCB7OQO6HSbcQlw7uQqlhq2QrWA2TsnfBa6b5IhMWXrYGrPPQRkmnN+SdAGM7S+ef8NKF2Gxc889wL47cunKLiruhlRJQlyIoC7PmCgMTb5Ful5Rkr5zUATWQirCLxZSRFYCtoRo6c1Lw/8xcp0J41j2nr1qZKzUHMva0q2QL4hLw6VSH18pe9GCqkxwqO+Sc2PRIfiASmUFFO0KQz+PpYEAt36e30sY0hg8LYhI3ZTGlgsMZFkB2CAng6Yw5ZrQETQ+27SWtHGW1QqMghD8IoSlJP5sYwOUoBquYt9VhtAABKMGkwIJHplXZR88vho+b1D+QP+Z2Yvvmoz9e3TyRM3pMi4ur1K8ytlqNMk5KF4OFdwhailc4E6zKURZS9v5XMS/lSRdiHr4YcWUkheCyVZO8giruQ=
  app: lz_manager
  on:
    repo: DanielSchneider93/lz_manager
