language: ruby
rvm:
- 2.4
script:
- bundle exec rails db:migrate
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec spec

deploy:
  provider: heroku
  api_key:
    secure: nt81dX/9OZ2HMz3EEdMse+e71kONCIA0RiJ4SaKJsbcr0JlX2R1vnFFHSomAbTJAB/muRk5oOIp6cxxsz7XuqWqEmLrmt6HRo4+fuhhLyetiOEF/754IAH8sJsWLIfGdOFQTN6Otwr0/ZFAjkkBIZVOcpHjVqtg7iESkoU1kQH4A7Lc2UHINwmgQz0qbpVw18OYeB5g0q2cAcUjUje9R2ZzAc/y5jG9lBJ0+FNecFgILr345aUyj+0PswFW9e/aX1nukZiVZo2icLj4RnOqqh4w0ZjFM1uT8tr+kMRRBXJfuNgyxJw4UICYX+6QJopdTXf8exrqwQMy4zGBy3ZvvDJswAnAHrKK7uJM139MJYeNBKrPfUsNlDUR1QrJogqUQwzQSfEGAi6sbC6PtoOeqBloU6qBx41deLg904j3XknYeO5VDuXl1azTtmRKcwKHGfWjST/lLJMQy8NcvVghmO4ddIW+BkmAAXm5Ycu+reWPDFh9Aj+AoXf6J7coMwK/3k42MnVqRUz/LPmXP/+01tLKqw/hNL7DGjI4EwCg/kohva6Wfhl6Pl35uYk1ypdpOpyJPOmUAoUpX1MhZ7YMGVZfi4KDVj3vcrA3NiK4bnsWgBFOU5ljg4dJEu4Cz2owDcDtWyUrxogwb7fWSpnrfjrzHFJyvQzCPyc6ExNfEzjA=
  app: lzmanager
  on:
    repo: DanielSchneider93/lz_manager
  run:  bundle exec rails db:migrate
